content_path: .

template_path: templates
template_static_path: template_assets
default_template: template-web.html
default_pdf_template: template-pdf.html
filter_paths:
    - custom_filters
    - more_custom_filters

targets:
    -   name: everything
        display_name: Target with ALL THE EXAMPLES™

    -   name: filterdemos
        display_name: Target with just the filter example pages

    -   name: conditionals
        display_name: Conditional Text Target
        condition: tests-2

pages:
    -   md: includes.md
        html: test-includes.html
        category: Tests
        targets:
            - everything

    -   name: Conditionals Test
        category: Tests
        md: conditionals.md
        html: test-conditionals.html
        targets:
            - everything
            - conditionals

    -   name: Lists and Code Blocks Demo
        category: Tests
        md: lists-and-codeblocks.md
        html: test-lists-and-codeblocks.html
        targets:
            - everything

    -   name: GitHub Markdown Compatibility
        category: Tests
        md: gfm-compat.md
        html: test-gfm-compat.html
        targets:
            - everything

    -   md: filter-examples/callouts.md
        html: filter-callouts.html
        category: Filters
        targets:
            - everything
            - filterdemos
        filters:
            - callouts

    -   md: filter-examples/xrefs.md
        html: filter-xrefs.html
        category: Filters
        targets:
            - everything
            - filterdemos
        filters:
            - xrefs

    -   md: filter-examples/buttonize.md
        html: filter-buttonize.html
        category: Filters
        targets:
            - everything
            - filterdemos
        filters:
            - buttonize

    -   md: filter-examples/patriots.md
        html: filter-patriots.html
        category: Filters
        targets:
            - everything
            - filterdemos
        filters:
            - patriots

    -   md: filter-examples/patriots.md
        name: Custom Filter 2
        html: filter-patriots2.html
        category: Filters
        targets:
            - everything
            - filterdemos
        filters:
            - patriots2

    -   md: filter-examples/badges.md
        html: filter-badges.html
        category: Filters
        targets:
            - everything
            - filterdemos
        filters:
            - badges

# -------------------- Style Checker Rules ------------------------
word_substitutions_file: plainlanguage_words.yaml
phrase_substitutions_file: plainlanguage_phrases.yaml
